on:
  push:
    branches:
     - main

jobs:
  webclient:
    name: Build Web Client
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webclient

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package

    - run: cd target && zip -r webclient.zip js

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: rs2-client
        path: webclient/target/webclient.zip
